/* eslint-disable @typescript-eslint/no-explicit-any */
"use client"

// This file is auto-generated by the ORMI CLI

import { PluginRegistry } from "ormi-core/plugins";

const registry : PluginRegistry = {
    "ormi-fligth-indicator": import("ormi-fligth-indicator") as any,
    "ormi-random": import("ormi-random") as any,
    "ormi-ros-2": import("ormi-ros-2") as any,
    "ormi-standart-widgets": import("ormi-standart-widgets") as any,
}

export default registry;