# Use the official ROS2 Docker image as the base image
FROM ros:jazzy

WORKDIR /ws_rosbridge
SHELL ["/bin/bash", "-c"]

# Install build dependencies
RUN apt-get update && apt-get install -y \
    git \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*

#RUN git clone --recursive --branch ros2 https://github.com/RobotWebTools/rosbridge_suite.git /ws_rosbridge/src/rosbridge_suite
RUN git clone --recursive --branch=ros2     https://github.com/RobotWebTools/rosbridge_suite.git      /ws_rosbridge/src/rosbridge_suite
# RUN git clone --recursive                   https://github.com/FlorianLebecque/ROS2CustomMSGCompil.git  /ws_rosbridge/src/ROS2CustomMSGCompil
# RUN git clone --recursive --branch=jazzy   https://github.com/ros-planning/navigation_msgs.git         /ws_rosbridge/src/navigation_msgs
# RUN git clone --recursive --branch=ros2     https://github.com/ros-perception/pcl_msgs.git              /ws_rosbridge/src/pcl_msgs

RUN cd /ws_rosbridge &&\
    source /opt/ros/${ROS_DISTRO}/setup.bash &&\
    apt-get update -y &&\
    apt-get install -y python3-rosdep \
    && source /opt/ros/${ROS_DISTRO}/setup.bash \
    && rm /etc/ros/rosdep/sources.list.d/20-default.list \
    && rosdep init \
    && rosdep update \
    && rosdep install -i --from-path src --rosdistro ${ROS_DISTRO} -y \
    && colcon build

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3-pip \
    ros-$ROS_DISTRO-rmw-cyclonedds-cpp

ENV RMW_IMPLEMENTATION rmw_cyclonedds_cpp

EXPOSE 9090

COPY ros_entrypoint.sh /sbin/ros_entrypoint.sh
RUN chmod 755 /sbin/ros_entrypoint.sh

ENTRYPOINT ["/sbin/ros_entrypoint.sh"]
CMD ["bash"]