services:
    core:
        container_name: ormi_core
        image: ghcr.io/rma-robotics-autonomous-systems/ormi:latest
        network_mode: host
        # build:
        # context: .
        # dockerfile: Dockerfile.ormi_core
        restart: unless-stopped
        environment:
            DATABASE_URL: postgresql://rasappdbuser:rasappdbpwd@localhost:5432/rasapppostgresqldb
            NEXTAUTH_URL: http://localhost:3000
            NEXTAUTH_SECRET: change-me-in-production
            APP_URL: http://localhost:3000
        labels:
            - com.centurylinklabs.watchtower.scope=ormi
        depends_on:
            postgres:
                condition: service_healthy

    watchtower:
        image: containrrr/watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            WATCHTOWER_POLL_INTERVAL: 30
            WATCHTOWER_CLEANUP: true
            WATCHTOWER_SCOPE: ormi
        command: --scope ormi
        labels:
            - com.centurylinklabs.watchtower.scope=ormi

    postgres:
        image: postgres:17.0-alpine
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: rasappdbuser
            POSTGRES_PASSWORD: rasappdbpwd
            POSTGRES_DB: rasapppostgresqldb
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - ./postgres:/var/lib/postgresql/data
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U rasappdbuser -d rasapppostgresqldb",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
